# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: ldzSpace的博客
SEOTitle: ldz博客 | MY Blog
header-img: img/post-bg-desk.jpg
keyword: "liudazhi‘s Blog"
email: 842129948@qq.com 
description: >- # this means to ignore newlines until "baseurl:"
   不积跬步无以至千里
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
jianshu_username: ldzSpace
github_username: ldzSpace

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM   
theme: minima
plugins:
  - jekyll-feed

# Sidebar settings
sidebar: true  #添加侧边栏
sidebar-about-description: "我就是我,不一样的烟火"
sidebar-avatar: /img/avatar_head.jpg     #你的大头贴，请使用绝对地址.注意：名字区分大小写！后缀名也是


permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`

plugins: [jekyll-paginate]
#gems: [jekyll-paginate]

# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: f2c84e7629bb1446c1a4                            #生成的clientID
  clientSecret: ca6d6139d1e1b8c43f8b2e19492ddcac8b322d0d    #生成的clientSecret
  repo: qiubaiying.github.io    #仓库名称
  owner: qiubaiying    #github用户名
  admin: qiubaiying
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
ga_track_id: 'UA-90855596-1'            # Format: UA-xxxxxx-xx
ga_domain: qiubaiying.top               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto


# Friends
friends: [
    {
        title: "Paper",
        href: "https://paper.seebug.org/415/"
    },{
        title: "安全",
        href: "http://www.droidsec.cn/ios%E5%AE%89%E5%85%A8%E5%AD%A6%E4%B9%A0%E8%B5%84%E6%96%99%E6%B1%87%E6%80%BB/"
    },{
        title: "IOS安全Wiki",
        href: "https://wizardforcel.gitbooks.io/ios-sec-wiki/content/chapter4/issue4-4.html"
    },{
        title: "Apple Developer",
        href: "https://developer.apple.com/"
    }
]

